"use client";
import { useState } from "react";
const BG="#0B1120",CARD="#111827",BORDER="#1E3A5F",TEXT="#E2E8F0",MUTED="#94A3B8",GREEN="#16A34A",RED="#DC2626",ORANGE="#F97316",AMBER="#854F0B";
const QS=[
  {q:"LinkedList.get(index) est :",o:["O(1)","O(n)","O(log n)","O(n²)"],c:1,e:"Parcours séquentiel du début → O(n). ArrayList.get(i) serait O(1)."},
  {q:"Complexité de HashMap.get() en moyenne ?",o:["O(n)","O(log n)","O(1)","O(n²)"],c:2,e:"Hash function → accès direct O(1) en moyenne."},
  {q:"Collision dans HashMap signifie :",o:["Erreur fatale","Deux clés donnent le même index hash","HashMap plein","Perte de données"],c:1,e:"Résolu par chaînage (LinkedList dans le bucket) ou adressage ouvert."},
  {q:"BST inorder donne les éléments :",o:["Ordre d'insertion","Triés (croissant)","Ordre inverse","Aléatoirement"],c:1,e:"Inorder (Gauche-Racine-Droite) sur BST = éléments triés."},
  {q:"assertThrows en JUnit 5 sert à :",o:["Lancer une exception","Vérifier qu'une exception EST lancée","Ignorer les exceptions","Attraper les erreurs"],c:1,e:"assertThrows(Class, lambda) vérifie que le code lance bien cette exception."},
  {q:"@BeforeEach s'exécute :",o:["Une seule fois","Avant CHAQUE test","Après chaque test","Jamais"],c:1,e:"@BeforeEach = exécuté avant chaque méthode @Test (setup frais)."},
  {q:"throw vs throws :",o:["Identiques","throw LANCE, throws DÉCLARE","throw déclare, throws lance","throw = JUnit 4"],c:1,e:"throw new Exception() lance. throws Exception déclare dans la signature."},
  {q:"finally s'exécute :",o:["Seulement si exception","Seulement si pas exception","TOUJOURS","Jamais"],c:2,e:"finally s'exécute toujours, exception ou pas. Idéal pour fermer des ressources."},
  {q:"ArrayDeque utilise :",o:["Liste chaînée","Tableau circulaire","Arbre binaire","HashMap"],c:1,e:"ArrayDeque = tableau circulaire avec head/tail. Plus rapide que LinkedList comme Queue."},
  {q:"Pour O(n²), si n double, le temps est multiplié par :",o:["2","4","8","n"],c:1,e:"n² : (2n)² = 4n². Multiplié par 4."},
  {q:"Quelle annotation JUnit 5 pour un test ?",o:["@TestCase","@Test","@RunWith","@JUnit"],c:1,e:"@Test (import org.junit.jupiter.api.Test) marque une méthode de test."},
  {q:"try-catch-finally : quel bloc est obligatoire ?",o:["catch","finally","Les deux","try + au moins catch OU finally"],c:3,e:"try doit être suivi d'au moins un catch ou un finally (ou les deux)."},
  {q:"Différence LinkedList vs ArrayList pour add(0, e) :",o:["LinkedList O(1), ArrayList O(n)","Identiques","ArrayList O(1), LinkedList O(n)","Les deux O(log n)"],c:0,e:"LinkedList insère en tête en O(1) (changer un pointeur). ArrayList doit décaler tous les éléments O(n)."},
  {q:"Queue FIFO : premier entré = :",o:["Dernier sorti","Premier sorti","Jamais sorti","Aléatoire"],c:1,e:"FIFO = First In, First Out. Le premier entré est le premier sorti."},
  {q:"Complexité de Bubble Sort :",o:["O(n)","O(n log n)","O(n²)","O(log n)"],c:2,e:"Bubble Sort compare des paires adjacentes. Deux boucles imbriquées → O(n²)."},
  {q:"Avantage de LinkedList sur ArrayList :",o:["Accès par index O(1)","Insertion/suppression en milieu O(1) si on a le noeud","Moins de mémoire","Recherche O(log n)"],c:1,e:"LinkedList excelle en insertion/suppression (changer des pointeurs) mais paye l'accès séquentiel."},
  {q:"HashMap stocke les paires :",o:["Triées par clé","Dans un tableau indexé par hash","Dans une liste chaînée","Dans un arbre"],c:1,e:"Les clés sont hashées pour obtenir un index dans le tableau interne."},
  {q:"assertEquals(expected, actual) en JUnit :",o:["Compare les références","Compare les valeurs avec equals()","Compare les types","Compare les hashs"],c:1,e:"assertEquals utilise equals() pour comparer. assertSame() comparerait les références."},
  {q:"Checked vs Unchecked Exception :",o:["Identiques","Checked = le compilateur force le catch. Unchecked = RuntimeException","Checked = runtime, Unchecked = compilation","Checked est plus grave"],c:1,e:"Checked (IOException) = obligé de catch/throws. Unchecked (NullPointerException) = pas obligé."},
  {q:"Quick Sort complexité moyenne :",o:["O(n)","O(n log n)","O(n²)","O(log n)"],c:1,e:"Quick Sort partitionne et trie récursivement. Moyenne O(n log n), pire cas O(n²)."},
];
export default function BossLO3(){
  const[started,setStarted]=useState(false);const[idx,setIdx]=useState(0);const[score,setScore]=useState(0);
  const[sel,setSel]=useState<number|null>(null);const[show,setShow]=useState(false);
  const[shuffled]=useState(()=>[...QS].sort(()=>Math.random()-0.5).slice(0,15));
  if(!started)return(<div style={{minHeight:"100vh",background:BG,color:TEXT,padding:"3rem 1rem"}}><div style={{maxWidth:600,margin:"0 auto",textAlign:"center"}}><div style={{fontSize:60}}></div><div style={{fontSize:13,color:ORANGE,fontWeight:600,letterSpacing:2,textTransform:"uppercase"}}>Boss Fight — Monde 3</div><h1 style={{fontSize:28,fontWeight:700,margin:"0.5rem 0"}}>LO3 : Implémenter & Tester</h1><p style={{color:MUTED,marginBottom:4}}>15 questions aléatoires sur 20</p><p style={{color:MUTED,fontSize:13,marginBottom:24}}>LinkedList • HashMap • BST • Queue • JUnit 5 • Exceptions • Tri</p><button onClick={()=>setStarted(true)} style={{padding:"12px 32px",background:ORANGE,color:"white",border:"none",borderRadius:10,fontSize:18,fontWeight:700,cursor:"pointer"}}>Commencer le Boss</button></div></div>);
  if(idx>=shuffled.length){const p=Math.round(score/shuffled.length*100);const msg=p>=80?"BOSS VAINCU !":p>=60?"Presque... Réessayez !":"Le boss vous a battu !";return(<div style={{minHeight:"100vh",background:BG,color:TEXT,padding:"3rem 1rem"}}><div style={{maxWidth:500,margin:"0 auto",textAlign:"center"}}><div style={{fontSize:80,fontWeight:800,color:p>=80?GREEN:p>=60?ORANGE:RED}}>{score}/{shuffled.length}</div><div style={{fontSize:20,fontWeight:600,margin:"0.5rem 0"}}>{msg}</div><button onClick={()=>{setIdx(0);setScore(0);setStarted(false)}} style={{marginTop:16,padding:"10px 24px",background:ORANGE,color:"white",border:"none",borderRadius:8,fontWeight:600,cursor:"pointer"}}>Rejouer</button></div></div>)}
  const q=shuffled[idx];
  return(<div style={{minHeight:"100vh",background:BG,color:TEXT,padding:"1.5rem 1rem"}}><div style={{maxWidth:650,margin:"0 auto"}}><div style={{fontSize:13,color:MUTED,marginBottom:8}}> {idx+1}/{shuffled.length} | Score: {score}</div><div style={{height:4,background:BORDER,borderRadius:2,marginBottom:16}}><div style={{height:4,background:ORANGE,borderRadius:2,width:`${(idx+1)/shuffled.length*100}%`}}/></div><p style={{fontSize:16,fontWeight:600,marginBottom:12}}>{q.q}</p><div style={{display:"grid",gap:8}}>{q.o.map((o,i)=>{let bg=CARD,bd=BORDER;if(show){if(i===q.c){bg=GREEN+"20";bd=GREEN}else if(i===sel){bg=RED+"20";bd=RED}}return(<button key={i} onClick={()=>{if(show)return;setSel(i);setShow(true);if(i===q.c)setScore(s=>s+1)}} disabled={show} style={{padding:"10px 14px",border:`2px solid ${bd}`,borderRadius:8,background:bg,cursor:show?"default":"pointer",textAlign:"left",fontSize:14,color:TEXT}}>{o}</button>)})}</div>{show&&<><div style={{marginTop:10,padding:"10px 14px",background:GREEN+"15",borderRadius:8,fontSize:13,color:GREEN}}>{q.e}</div><button onClick={()=>{setIdx(i=>i+1);setSel(null);setShow(false)}} style={{marginTop:10,width:"100%",padding:"10px",background:ORANGE,color:"white",border:"none",borderRadius:8,fontWeight:600,cursor:"pointer"}}>Suivant →</button></>}</div></div>);
}
