"use client";
import { useState } from "react";
const BG="#0B1120",CARD="#111827",BORDER="#1E3A5F",TEXT="#E2E8F0",MUTED="#94A3B8",GREEN="#16A34A",RED="#DC2626",ORANGE="#F97316",AMBER="#D97706";
const QS=[
  {q:"O(1) signifie :",o:["Le programme fait 1 opération","Temps constant quelle que soit la taille","Toujours 1 seconde","Erreur"],c:1,e:"O(1) = temps constant, indépendant de n."},
  {q:"O(n) vs O(n²) pour n=10000 :",o:["Presque pareil","O(n) = 10000, O(n²) = 100 millions","O(n²) est plus rapide","Impossible à comparer"],c:1,e:"10000 vs 100000000. La différence est énorme pour les grands n !"},
  {q:"Pourquoi O(2n) = O(n) ?",o:["Erreur mathématique","Les constantes sont ignorées en Big O","2n = n","Simplification pour débutants"],c:1,e:"Big O ignore les constantes : ce qui compte c'est la tendance de croissance."},
  {q:"Big O vs Big Omega :",o:["O = pire cas, Ω = meilleur cas","O = borne supérieure, Ω = borne inférieure","Identiques","O = temps, Ω = espace"],c:1,e:"O = au plus (upper bound). Ω = au moins (lower bound). Θ = les deux (tight bound)."},
  {q:"Tri optimal par comparaison :",o:["O(n)","O(n log n)","O(n²)","O(log n)"],c:1,e:"O(n log n) est la borne inférieure théorique. Merge Sort et Heap Sort l'atteignent."},
  {q:"HashMap O(1) moyen, mais O(n) quand :",o:["Jamais","Beaucoup de collisions (toutes les clés dans le même bucket)","HashMap plein","Clés nulles"],c:1,e:"Si le hash distribue mal → chaîne longue → dégénère en O(n)."},
  {q:"Espace mémoire LinkedList vs ArrayList :",o:["LinkedList utilise moins","LinkedList utilise plus (pointeurs next/prev)","Identique","Dépend du système"],c:1,e:"LinkedList stocke des pointeurs supplémentaires (next, prev). ArrayList stocke juste les données dans un tableau."},
  {q:"Trade-off temps vs espace : HashMap utilise :",o:["Plus de mémoire pour un accès plus rapide","Moins de mémoire","Autant que ArrayList","Aucun compromis"],c:0,e:"HashMap sacrifie de la mémoire (tableau + buckets) pour obtenir un accès O(1)."},
  {q:"Algorithme O(n log n) avec n=1 million ≈ :",o:["1 million ops","20 millions ops","1 billion ops","1 trillion ops"],c:1,e:"n × log₂(n) = 10⁶ × 20 ≈ 20 millions. Très raisonnable !"},
  {q:"Si un algo O(n²) prend 1s pour n=1000, pour n=2000 :",o:["2 secondes","4 secondes","8 secondes","1000 secondes"],c:1,e:"n double → temps ×4 (car n² = (2n)² = 4n²)."},
  {q:"BST équilibré recherche en :",o:["O(1)","O(log n)","O(n)","O(n²)"],c:1,e:"BST équilibré : à chaque étape on élimine la moitié → O(log n)."},
  {q:"Quel algorithme de tri est in-place (O(1) espace) ?",o:["Merge Sort","Quick Sort","Counting Sort","Radix Sort"],c:1,e:"Quick Sort trie sur place (partitionnement). Merge Sort a besoin d'espace O(n)."},
  {q:"Complexité de la recherche binaire :",o:["O(n)","O(log n)","O(1)","O(n²)"],c:1,e:"On divise par 2 à chaque étape. log₂(n) étapes max."},
  {q:"Efficacité = :",o:["Écrire le moins de code","Utiliser les ressources (temps, mémoire) de manière optimale","Coder rapidement","Utiliser le dernier framework"],c:1,e:"L'efficacité mesure l'utilisation optimale des ressources informatiques."},
  {q:"Parallélisme peut améliorer :",o:["La complexité Big O","Le temps réel d'exécution sur multi-cœur","La correction du code","La lisibilité"],c:1,e:"Le parallélisme divise le travail entre cœurs → temps réel réduit, mais Big O ne change pas."},
  {q:"ArrayList.add(e) en fin est :",o:["Toujours O(1)","O(1) amorti (parfois O(n) pour resize)","O(n)","O(log n)"],c:1,e:"Normalement O(1), mais quand le tableau est plein → copie en O(n). Amorti = O(1) en moyenne."},
  {q:"Stack LIFO vs Queue FIFO : pour undo/redo :",o:["Queue","Stack","Les deux","Ni l'un ni l'autre"],c:1,e:"Undo = dépiler la dernière action (LIFO). Stack est le choix naturel."},
  {q:"Complexité spatiale d'un algorithme récursif de profondeur n :",o:["O(1)","O(n) (pile d'appels)","O(n²)","O(log n)"],c:1,e:"Chaque appel récursif empile un frame → O(n) sur la call stack."},
  {q:"Quand préférer LinkedList à ArrayList ?",o:["Toujours","Insertions/suppressions fréquentes en milieu","Accès aléatoire fréquent","Jamais"],c:1,e:"LinkedList excelle en insertion/suppression (O(1) avec référence au noeud). ArrayList excelle en accès aléatoire O(1)."},
  {q:"Graph DFS utilise :",o:["Queue","Stack","HashMap","Array"],c:1,e:"DFS = Depth-First Search = exploration en profondeur. Utilise un Stack (ou la récursion = call stack)."},
];
export default function BossLO4(){
  const[started,setStarted]=useState(false);const[idx,setIdx]=useState(0);const[score,setScore]=useState(0);
  const[sel,setSel]=useState<number|null>(null);const[show,setShow]=useState(false);
  const[shuffled]=useState(()=>[...QS].sort(()=>Math.random()-0.5).slice(0,15));
  if(!started)return(<div style={{minHeight:"100vh",background:BG,color:TEXT,padding:"3rem 1rem"}}><div style={{maxWidth:600,margin:"0 auto",textAlign:"center"}}><div style={{fontSize:60}}></div><div style={{fontSize:13,color:AMBER,fontWeight:600,letterSpacing:2,textTransform:"uppercase"}}>Boss Fight — Monde 4</div><h1 style={{fontSize:28,fontWeight:700,margin:"0.5rem 0"}}>LO4 : Efficacité & Complexité</h1><p style={{color:MUTED,marginBottom:4}}>15 questions aléatoires sur 20</p><p style={{color:MUTED,fontSize:13,marginBottom:24}}>Big O • Ω • Θ • Trade-offs • Tri • Espace • Parallélisme</p><button onClick={()=>setStarted(true)} style={{padding:"12px 32px",background:AMBER,color:"white",border:"none",borderRadius:10,fontSize:18,fontWeight:700,cursor:"pointer"}}>Commencer le Boss</button></div></div>);
  if(idx>=shuffled.length){const p=Math.round(score/shuffled.length*100);const msg=p>=80?"BOSS VAINCU !":p>=60?"Presque... Réessayez !":"Le boss vous a battu !";return(<div style={{minHeight:"100vh",background:BG,color:TEXT,padding:"3rem 1rem"}}><div style={{maxWidth:500,margin:"0 auto",textAlign:"center"}}><div style={{fontSize:80,fontWeight:800,color:p>=80?GREEN:p>=60?ORANGE:RED}}>{score}/{shuffled.length}</div><div style={{fontSize:20,fontWeight:600,margin:"0.5rem 0"}}>{msg}</div><button onClick={()=>{setIdx(0);setScore(0);setStarted(false)}} style={{marginTop:16,padding:"10px 24px",background:AMBER,color:"white",border:"none",borderRadius:8,fontWeight:600,cursor:"pointer"}}>Rejouer</button></div></div>)}
  const q=shuffled[idx];
  return(<div style={{minHeight:"100vh",background:BG,color:TEXT,padding:"1.5rem 1rem"}}><div style={{maxWidth:650,margin:"0 auto"}}><div style={{fontSize:13,color:MUTED,marginBottom:8}}> Boss {idx+1}/{shuffled.length} | Score: {score}</div><div style={{height:4,background:BORDER,borderRadius:2,marginBottom:16}}><div style={{height:4,background:AMBER,borderRadius:2,width:`${(idx+1)/shuffled.length*100}%`}}/></div><p style={{fontSize:16,fontWeight:600,marginBottom:12}}>{q.q}</p><div style={{display:"grid",gap:8}}>{q.o.map((o,i)=>{let bg=CARD,bd=BORDER;if(show){if(i===q.c){bg=GREEN+"20";bd=GREEN}else if(i===sel){bg=RED+"20";bd=RED}}return(<button key={i} onClick={()=>{if(show)return;setSel(i);setShow(true);if(i===q.c)setScore(s=>s+1)}} disabled={show} style={{padding:"10px 14px",border:`2px solid ${bd}`,borderRadius:8,background:bg,cursor:show?"default":"pointer",textAlign:"left",fontSize:14,color:TEXT}}>{o}</button>)})}</div>{show&&<><div style={{marginTop:10,padding:"10px 14px",background:GREEN+"15",borderRadius:8,fontSize:13,color:GREEN}}>{q.e}</div><button onClick={()=>{setIdx(i=>i+1);setSel(null);setShow(false)}} style={{marginTop:10,width:"100%",padding:"10px",background:AMBER,color:"white",border:"none",borderRadius:8,fontWeight:600,cursor:"pointer"}}>Suivant →</button></>}</div></div>);
}
