"use client";
import CommentWidget from "@/components/CommentWidget";
import Link from "next/link";
import { useState } from "react";
import TopBar from "@/components/TopBar";
const BG="#0B1120",CARD="#111827",BORDER="#1E3A5F",TEXT="#E2E8F0",MUTED="#94A3B8",GREEN="#16A34A",TEAL="#0891B2",RED="#DC2626",ORANGE="#F97316";
const QS=[
  {q:"En notation impérative, PRE signifie :",o:["Précondition — vrai AVANT l'appel","Postcondition","Prefix du nom","Premier paramètre"],c:0,e:"PRE = ce qui doit être vrai AVANT d'appeler l'opération."},
  {q:"Quel axiome caractérise le Stack ?",o:["pop(push(S,e)) = <e,S>","push(pop(S)) = S","peek(enqueue(S,e)) = e","size(new) = 1"],c:0,e:"Push puis pop retourne l'élément et le stack original (LIFO)."},
  {q:"VDM est basé sur :",o:["Des diagrammes graphiques","La logique mathématique (pré/post-conditions)","Le langage Java","Des automates"],c:1,e:"VDM = Vienna Development Method = logique formelle avec ≜, pré/post/invariants."},
  {q:"SDL utilise :",o:["Des formules mathématiques","Des diagrammes d'automates (états/transitions)","Du pseudo-code","Des tests JUnit"],c:1,e:"SDL = Specification and Description Language = diagrammes graphiques pour systèmes réactifs."},
  {q:"L'encapsulation regroupe :",o:["Données + opérations dans une unité avec contrôle d'accès","Seulement les données","Seulement les méthodes","Les fichiers .jar"],c:0,e:"Encapsulation = regrouper attributs + méthodes avec private/public."},
  {q:"Information Hiding cache :",o:["Le nom de la classe","L'implémentation derrière une interface publique","Les commentaires","Tout le code"],c:1,e:"On expose le QUOI (interface), on cache le COMMENT (implémentation)."},
  {q:"Quel modificateur Java est le plus restrictif ?",o:["public","protected","private","default"],c:2,e:"private = accessible UNIQUEMENT dans la classe elle-même."},
  {q:"Changer ArrayList→HashMap en interne, le code client :",o:["Doit tout réécrire","Ne change pas si l'interface reste la même","Crashe","Doit recompiler"],c:1,e:"Puissance de l'encapsulation : changement transparent si interface inchangée."},
  {q:"Les ADT impératifs sont la base de la POO car :",o:["Ils sont en Java","Encapsulation+abstraction+contrats viennent des ADT","Ils remplacent la POO","C'est historique uniquement"],c:1,e:"Les concepts fondamentaux de la POO viennent directement des ADT."},
  {q:"La POO ajoute aux ADT :",o:["Rien","Héritage et polymorphisme","La vitesse","Les exceptions"],c:1,e:"POO = ADT + héritage (extends) + polymorphisme (interface/implements)."},
  {q:"Quel Design Pattern = une seule instance ?",o:["Factory","Singleton","Observer","Builder"],c:1,e:"Singleton : constructeur privé + getInstance() → une seule instance."},
  {q:"Factory Method permet de :",o:["Observer des changements","Laisser la sous-classe décider quel objet créer","Garantir une seule instance","Construire étape par étape"],c:1,e:"Factory = pseudo-polymorphisme à l'instanciation."},
  {q:"Observer Pattern sert à :",o:["Créer un objet","Notifier les abonnés quand l'état change","Adapter des interfaces","Trier des données"],c:1,e:"Observer = pub/sub. Changement → notification automatique."},
  {q:"Error-condition en Java se traduit par :",o:["Un commentaire","Une exception (throw/catch)","Un return false","Un System.exit()"],c:1,e:"Violation de pré-condition → throw exception. Gestion → try/catch."},
  {q:"Interface Java = :",o:["Implémentation complète","ADT : spécification sans implémentation","Classe abstraite","Package"],c:1,e:"Interface = QUOI sans COMMENT = traduction directe d'un ADT."},
  {q:"ASN.1 sert à :",o:["Compiler du Java","Décrire la structure des données échangées entre systèmes","Dessiner des diagrammes","Tester le code"],c:1,e:"ASN.1 = notation standard pour la structure des données, indépendante du langage."},
  {q:"Composite Pattern compose des objets en :",o:["Liste simple","Structure d'arbre","File d'attente","Pile"],c:1,e:"Composite = arbre. Client traite feuilles et composites uniformément."},
  {q:"Strategy Pattern permet de :",o:["Créer une instance unique","Observer des changements","Changer d'algorithme dynamiquement","Adapter des interfaces"],c:2,e:"Strategy = famille d'algorithmes interchangeables à runtime."},
  {q:"Pré-condition de pop() sur un Stack :",o:["Pile pleine","Pile non vide (isEmpty() == false)","Pile triée","Aucune"],c:1,e:"On ne peut pas pop() si la pile est vide."},
  {q:"Les 3 catégories de Design Patterns GoF :",o:["Création, Structure, Comportement","Simple, Moyen, Complexe","Input, Process, Output","Data, Logic, UI"],c:0,e:"GoF : Création (comment créer), Structure (comment composer), Comportement (comment interagir)."},
];
export default function BossLO2(){
  const[started,setStarted]=useState(false);const[idx,setIdx]=useState(0);const[score,setScore]=useState(0);
  const[sel,setSel]=useState<number|null>(null);const[show,setShow]=useState(false);
  const[shuffled]=useState(()=>[...QS].sort(()=>Math.random()-0.5).slice(0,15));
  if(!started)return(<div style={{minHeight:"100vh",background:BG,color:TEXT,padding:"3rem 1rem"}}><div style={{maxWidth:600,margin:"0 auto",textAlign:"center"}}><div style={{fontSize:60}}></div><div style={{fontSize:13,color:TEAL,fontWeight:600,letterSpacing:2,textTransform:"uppercase"}}>Boss Fight — Monde 2</div><h1 style={{fontSize:28,fontWeight:700,margin:"0.5rem 0"}}>LO2 : Notation, Encapsulation, Patterns</h1><p style={{color:MUTED,marginBottom:4}}>15 questions aléatoires sur 20</p><p style={{color:MUTED,fontSize:13,marginBottom:24}}>Spec formelle • VDM/SDL/ASN.1 • Encapsulation • Info Hiding • Interfaces • ADT→POO • Design Patterns • Conditions</p><button onClick={()=>setStarted(true)} style={{padding:"12px 32px",background:TEAL,color:"white",border:"none",borderRadius:10,fontSize:18,fontWeight:700,cursor:"pointer"}}>Commencer le Boss</button></div></div>);
  if(idx>=shuffled.length){const p=Math.round(score/shuffled.length*100);const msg=p>=80?"BOSS VAINCU !":p>=60?"Presque... Réessayez ! Réessayez !":"Le boss vous a battu. Révisez et retentez !";return(<div style={{minHeight:"100vh",background:BG,color:TEXT,padding:"3rem 1rem"}}><div style={{maxWidth:500,margin:"0 auto",textAlign:"center"}}><div style={{fontSize:80,fontWeight:800,color:p>=80?GREEN:p>=60?ORANGE:RED}}>{score}/{shuffled.length}</div><div style={{fontSize:20,fontWeight:600,margin:"0.5rem 0"}}>{msg}</div><button onClick={()=>{setIdx(0);setScore(0);setStarted(false)}} style={{marginTop:16,padding:"10px 24px",background:TEAL,color:"white",border:"none",borderRadius:8,fontWeight:600,cursor:"pointer"}}>Rejouer</button></div></div>)}
  const q=shuffled[idx];
  return(<div style={{minHeight:"100vh",background:BG,color:TEXT,padding:"1.5rem 1rem"}}><div style={{maxWidth:650,margin:"0 auto"}}><div style={{fontSize:13,color:MUTED,marginBottom:8}}> {idx+1}/{shuffled.length} | Score: {score}</div><div style={{height:4,background:BORDER,borderRadius:2,marginBottom:16}}><div style={{height:4,background:TEAL,borderRadius:2,width:`${(idx+1)/shuffled.length*100}%`}}/></div><p style={{fontSize:16,fontWeight:600,marginBottom:12}}>{q.q}</p><div style={{display:"grid",gap:8}}>{q.o.map((o,i)=>{let bg=CARD,bd=BORDER;if(show){if(i===q.c){bg=GREEN+"20";bd=GREEN}else if(i===sel){bg=RED+"20";bd=RED}}return(<button key={i} onClick={()=>{if(show)return;setSel(i);setShow(true);if(i===q.c)setScore(s=>s+1)}} disabled={show} style={{padding:"10px 14px",border:`2px solid ${bd}`,borderRadius:8,background:bg,cursor:show?"default":"pointer",textAlign:"left",fontSize:14,color:TEXT}}>{o}</button>)})}</div>{show&&<><div style={{marginTop:10,padding:"10px 14px",background:GREEN+"15",borderRadius:8,fontSize:13,color:GREEN}}>{q.e}</div><button onClick={()=>{setIdx(i=>i+1);setSel(null);setShow(false)}} style={{marginTop:10,width:"100%",padding:"10px",background:TEAL,color:"white",border:"none",borderRadius:8,fontWeight:600,cursor:"pointer"}}>Suivant →</button></>}</div></div>);
      }
